// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65dpNYKsO7Dt_W-4bGwSjA-4vJv8lS78',
    appId: '1:853777209557:web:7114f86937a9a0e47daa5c',
    messagingSenderId: '853777209557',
    projectId: 'fmms-af951',
    authDomain: 'fmms-af951.firebaseapp.com',
    storageBucket: 'fmms-af951.appspot.com',
    measurementId: 'G-M4KGSDVXKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnUK75Ghfu8-tWWuhNmN4DWPNlPkscWB4',
    appId: '1:853777209557:android:290531878ce895b27daa5c',
    messagingSenderId: '853777209557',
    projectId: 'fmms-af951',
    storageBucket: 'fmms-af951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTsXgz81cJ8Bi9yyPTOhQD0cSq21svDm0',
    appId: '1:853777209557:ios:fe197279a1c420557daa5c',
    messagingSenderId: '853777209557',
    projectId: 'fmms-af951',
    storageBucket: 'fmms-af951.appspot.com',
    iosBundleId: 'com.example.fmms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTsXgz81cJ8Bi9yyPTOhQD0cSq21svDm0',
    appId: '1:853777209557:ios:dc312afc60cb01ec7daa5c',
    messagingSenderId: '853777209557',
    projectId: 'fmms-af951',
    storageBucket: 'fmms-af951.appspot.com',
    iosBundleId: 'com.example.fmms.RunnerTests',
  );
}
